[package]
name = "autd3-gain-holo"
version = "14.2.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Holo (Multiple foci) Gain for AUTD."
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
assert_approx_eq = { version = "1.1.0", optional = true }
autd3-core = { path = "../autd3-core", version = "14.2.2" }
autd3-derive = { path = "../autd3-derive", version = "14.2.2" }
nalgebra = { version = "0.32.3", default-features = false, features = ["std"] }
rand = "0.8.5"
rayon = { version = "1.7.0", optional = true }
thiserror = "1.0.31"
criterion = { version = "0.5.1", features = ["html_reports"], optional = true }
bitvec = { version = "1.0.1", optional = true }

[features]
default = ["test-utilities"]
single_float = ["autd3-core/single_float"]
use_meter = ["autd3-core/use_meter"]
parallel = ["rayon", "autd3-core/parallel"]
test-utilities = ["criterion", "assert_approx_eq", "bitvec"]

[[bench]]
name = "holo"
path = "benches/holo.rs"
harness = false
