[package]
name = "SOEMAUTDServer"
version = "15.3.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"
license = "MIT"

description = "AUTDServer"
repository = "https://github.com/shinolab/autd3"
readme = "../README.md"
keywords = ["autd"]

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
autd3-protobuf = { path = "../../src/autd3-protobuf", version = "15.3.1" }
autd3-link-soem = { path = "../../src/autd3-link-soem", version = "15.3.1" }
autd3-driver = { path = "../../src/autd3-driver", version = "15.3.1" }
anyhow = "1.0.72"
ctrlc = "3.3.0"
tonic = "0.10.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
