[package]
name = "autd3-backend-arrayfire"
version = "14.2.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "ArrayFire Backend for AUTD3"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
arrayfire = "3.8.0"
autd3-core = { path = "../autd3-core", version = "14.2.1" }
autd3-gain-holo = { path = "../autd3-gain-holo", version = "14.2.1" }
nalgebra = { version = "0.32.1", default-features = false, features = ["std"] }
rand = "0.8.5"
rayon = { version = "1.7.0", optional = true }
thiserror = "1.0.31"

[dev-dependencies]
anyhow = "1.0.72"
assert_approx_eq = "1.1.0"
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["html_reports"] }

[features]
default = []
single_float = ["autd3-core/single_float", "autd3-gain-holo/single_float"]
use_meter = ["autd3-core/use_meter"]
parallel = ["rayon", "autd3-core/parallel"]
test-utilities = ["autd3-gain-holo/test-utilities"]

[[bench]]
name = "holo"
path = "benches/holo.rs"
harness = false
