[package]
name = "autd3-driver"
version = "17.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD3 driver"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
serde = { version = "1.0.188", features = ["derive"], optional = true }
bitflags = "2.0.2"
thiserror = "1.0.31"
nalgebra = { version = "0.32.3", default-features = false, features = ["std"] }
bitvec = "1.0.1"
async-trait = "0.1.74"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"], optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.51.1", features = ["Win32_Media_Multimedia", "Win32_System_Threading", "Win32_Foundation"] }

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.144"

[dev-dependencies]
rand = "0.8.5"
assert_approx_eq = "1.1.0"
itertools = "0.11.0"
memoffset = "0.9.0"
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }

[features]
default = []
single_float = []
use_meter = []
serde = ["dep:serde"]
sync = ["tokio"]
