[package]
name = "autd3"
version = "17.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD3 library"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-driver = { path = "../autd3-driver", version = "17.0.0", features = ["sync"] }
autd3-derive = { path = "../autd3-derive", version = "17.0.0" }
autd3-firmware-emulator = { path = "../autd3-firmware-emulator", version = "17.0.0" }
num = "0.4.0"
thiserror = "1.0.31"
bitvec = "1.0.1"
async-trait = "0.1.74"
tokio = { version = "1.34.0", features = ["rt-multi-thread"], optional = true }

[features]
default = []
firmware-v3 = ["autd3-driver/firmware-v3"]
sync = ["tokio"]
single_float = ["autd3-driver/single_float"]
use_meter = ["autd3-driver/use_meter"]

[dev-dependencies]
assert_approx_eq = "1.1.0"
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["html_reports"] }
itertools = "0.12.0"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }

[[bench]]
name = "gain"
path = "benches/gain/primitive.rs"
harness = false
