[package]
name = "autd3"
version = "15.3.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD3 library"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-driver = { path = "../autd3-driver", version = "15.3.1" }
autd3-derive = { path = "../autd3-derive", version = "15.3.1" }
autd3-firmware-emulator = { path = "../autd3-firmware-emulator", version = "15.3.1" }
num = "0.4.0"
thiserror = "1.0.31"
bitvec = "1.0.1"

[features]
default = []
single_float = ["autd3-driver/single_float"]
use_meter = ["autd3-driver/use_meter"]

[dev-dependencies]
assert_approx_eq = "1.1.0"
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["html_reports"] }
itertools = "0.11.0"

[[bench]]
name = "gain"
path = "benches/gain/primitive.rs"
harness = false
