[package]
name = "autd3-traits"
version = "2.5.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "Wav Modulation for AUTD."
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.18"
syn = "1.0.92"
