[package]
name = "autd3-link-twincat"
version = "15.1.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "Link of AUTD using TwinCAT."
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-driver = { path = "../autd3-driver", version = "15.1.2" }
itertools = { version = "0.11.0", optional = true }
libloading = { version = "0.8.0", optional = true }
thiserror = "1.0.31"

[build-dependencies]
cc = { version = "1.0.73", features = ["parallel"], optional = true }

[features]
local = ["libloading"]
remote = ["itertools", "cc"]
default = ["local"]
