[package]
name = "autd3-geometry-viewer"
version = "14.2.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD viewer for Geometry"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-core = { path = "../autd3-core", version = "14.2.2" }
bytemuck = { version = "1.13.1", features = ["derive", "extern_crate_std", "min_const_generics"] }
camera_controllers = "0.33.0"
cgmath = "0.18.0"
imgui = "0.11.0"
png = "0.17.8"
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
winit = "0.28.6"
gltf = "1.1.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.51.1", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }

[features]
default = []
use_meter = []
left_handed = []
enable_debug = []
