[package]
name = "autd3-link-simulator"
version = "15.2.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Link for autd-simulator"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-protobuf = { path = "../autd3-protobuf", version = "15.2.1" }
autd3-driver = { path = "../autd3-driver", version = "15.2.1" }
tokio = { version = "1.0", features = ["rt-multi-thread"] }
thiserror = "1.0.30"
tonic = "0.10.0"

[features]
default = []
single_float = ["autd3-driver/single_float"]
