[package]
name = "autd3-modulation-audio-file"
version = "15.1.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD library for Rust."
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
hound = "3.5.0"
autd3-driver = { path = "../autd3-driver", version = "15.1.0" }
autd3-derive = { path = "../autd3-derive", version = "15.1.0" }
wav_io = "0.1.8"
thiserror = "1.0.40"

[features]
default = []
single_float = ["autd3-driver/single_float"]
