[package]
name = "autd3-derive"
version = "15.2.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Wav Modulation for AUTD."
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.18"
syn = "2.0.3"

[features]
default = []
