[package]
name = "autd3-gain-holo"
version = "2.6.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "Holo (Multiple foci) Gain for AUTD."
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
anyhow = "1.0.57"
autd3-core = {path="../autd3-core", version="2.6.1"}
autd3-traits = {path="../autd3-traits", version="2.0.1"}
nalgebra = "0.31.0"
rand = "0.8.5"
thiserror = "1.0.31"
