[package]
name = "autd3-firmware-emulator"
version = "15.2.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD3 firmware emulator"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-driver = { path = "../autd3-driver", version = "15.2.1" }
num-integer = "0.1.45"
thiserror = "1.0.40"
