[package]
name = "autd3-protobuf"
version = "18.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Protocol Buffer"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
h2 = "0.4.0"
prost = { version = "0.12.0" }
tonic = { version = "0.10.0", default-features = false, features = ["prost", "codegen", "transport"] }
autd3-driver = { path = "../autd3-driver", version = "18.0.0" }
thiserror = "1.0.40"

[build-dependencies]
tonic-build = "0.10.0"
