[book]
authors = ["shun suzuki"]
language = "en"
multilingual = true
title = "AUTD3 Developers Manual v2.6.5"

src = "src"
destination = "book"

[preprocessor.index]
[preprocessor.links]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[[_TOC_]]"
max-level = 3

[output.html]
mathjax-support = true
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/shinolab/autd3"
git-branch = "master"
curly-quotes = true

[output.katex]

[output.linkcheck]

[preprocessor.katex]
macros = "katex_macro.txt"

[language-en]
src = "src/en"
destination = "book/en"

[language-jp]
src = "src/jp"
destination = "book/jp"
