[package]
name = "autd3-link-soem"
version = "17.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "Link of AUTD using SOEM."
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[build-dependencies]
cc = { version = "1.0.73", features = ["parallel"], optional = true }
glob = { version = "0.3.0", optional = true }

[dependencies]
async-trait = "0.1.74"
autd3-driver = { path = "../autd3-driver", version = "17.0.0" }
autd3-derive = { path = "../autd3-derive", version = "17.0.0" }
autd3-protobuf = { path = "../autd3-protobuf", version = "17.0.0", optional = true }
crossbeam-channel = { version = "0.5.4", optional = true }
thiserror = { version = "1.0.30", optional = true }
time = { version = "0.3.23", default-features = false, features = ["std"], optional = true }
tonic = { version = "0.10.0", optional = true }
tokio = { version = "1.33.0", features = ["rt-multi-thread"], optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.51.1", features = ["Win32_Foundation", "Win32_System_Performance", "Win32_Networking_WinSock", "Win32_System_SystemInformation"] }

[features]
local = ["cc", "glob", "crossbeam-channel", "time", "thiserror", "autd3-driver/sync"]
sync = ["tokio", "autd3-driver/sync"]
remote = ["autd3-protobuf", "tonic"]
default = ["local"]
all = ["local", "remote"]
