[book]
authors = ["Shun Suzuki"]
language = "ja"
multilingual = false
src = "src"
title = "AUTD3 FPGA Firmware Specification"

[rust]
edition = "2021"

[build]
create-missing = true

[preprocessor.index]
[preprocessor.links]
[preprocessor.katex]
macros = "katex_macro.txt"
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
[preprocessor.mermaid]
command = "mdbook-mermaid"
[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["theme/css/figure.css", "theme/css/table.css"]
git-repository-url = "https://github.com/shinolab/autd3-fpga"
git-branch = "master"

[output.katex]

[output.linkcheck]
