[package]
name = "license-checker"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
autd3-license-check = { path = "../autd3-license-check" }
cargo-license = "0.5.1"
cargo_metadata = "0.15.4"
