name: build-cs

on:
  push:
    branches:
      - 'develop'
  pull_request:
    types: [opened, reopened, review_requested]

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: build-cs-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: tj-actions/changed-files@v37
      id: changed-files
      with:
        files: |
          dotnet/cs/*.cs
          dotnet/cs/**/*.cs
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
      if: steps.changed-files.outputs.modified_files
    - name: Build with dotnet
      run: |
        cp LICENSE dotnet/cs/src/LICENSE.txt
        cd ./dotnet/cs/src
        dotnet build -c:Release
      if: steps.changed-files.outputs.modified_files
    - name: Test with dotnet
      run: |
        cd ./dotnet/cs/tests
        ./run_test.ps1
      if: steps.changed-files.outputs.modified_files && matrix.os == 'windows-latest'
    - name: Test with dotnet
      run: |
        cd ./dotnet/cs/tests
        chmod +x ./run_test.sh
        ./run_test.sh
      if: steps.changed-files.outputs.modified_files && matrix.os != 'windows-latest'
    - name: Build example with dotnet
      if: steps.changed-files.outputs.modified_files && matrix.os == 'windows-latest'
      run: |
        dotnet nuget add source $pwd/dotnet/cs/src/bin/Release -n autd3sharp_local
        cd ./dotnet/cs/example
        dotnet build -c:Release
